name: project2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  flutter_email_sender: ^7.0.0
  http: ^1.3.0
  mailer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/signin-assets/iOS/png@1x/dark/ios_dark_rd_ctn@1x.png
    - assets/signin-assets/iOS/png@1x/neutral/ios_neutral_rd_ctn@1x.png