// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAq6dmaIxqj3OTIXaCyjqjx5iR8-nLo2M',
    appId: '1:349499920166:web:ecbcd8633a6e3b3b473be7',
    messagingSenderId: '349499920166',
    projectId: 'cs458-791da',
    authDomain: 'cs458-791da.firebaseapp.com',
    storageBucket: 'cs458-791da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByLn5vWtu2a2S0s3aFnFOx4pT8tH6h8Ro',
    appId: '1:349499920166:android:b50d999b069305a4473be7',
    messagingSenderId: '349499920166',
    projectId: 'cs458-791da',
    storageBucket: 'cs458-791da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3HUYFRluRUbUQYedQZm-Pm_zpUyqmTE',
    appId: '1:349499920166:ios:c70fa11ee37bf945473be7',
    messagingSenderId: '349499920166',
    projectId: 'cs458-791da',
    storageBucket: 'cs458-791da.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3HUYFRluRUbUQYedQZm-Pm_zpUyqmTE',
    appId: '1:349499920166:ios:c70fa11ee37bf945473be7',
    messagingSenderId: '349499920166',
    projectId: 'cs458-791da',
    storageBucket: 'cs458-791da.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAq6dmaIxqj3OTIXaCyjqjx5iR8-nLo2M',
    appId: '1:349499920166:web:822b592eb12ec363473be7',
    messagingSenderId: '349499920166',
    projectId: 'cs458-791da',
    authDomain: 'cs458-791da.firebaseapp.com',
    storageBucket: 'cs458-791da.firebasestorage.app',
  );
}
